### ISSUE TITLE
Release a macOS app

### ISSUE THREAD

**Issue by rnons** [nonbili/fuji#4]
Related https://github.com/tauri-apps/tauri/issues/592

**Comment by i-am-the-slime** [comment]
Yes, please!

**Comment by rnons** [comment]
Fixed by https://github.com/nonbili/fuji/commit/38d16c1c17079ca49e745fb48ed64c4252a4f41a, please find a `.app.tgz` file on the [Release](https://github.com/nonbili/fuji/releases) page.

Thanks for sponsoring me. Fuji is in very early stage, adding a link for the first time maybe slow because a Heroku instance needs to start up, will be fixed in #1. Let me know if you have questions.

**Comment by i-am-the-slime** [comment]
@rnons Please don't feel pressured by the sponsoring. I was just very curious to try it out since this is the first time I heard of this alternative to Electron for building native apps with JS!
